apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: az756z94b-go
  janus-idp.io/tekton: az756z94b-go
  backstage.io/kubernetes-id: az756z94b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: az756z94b-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
